# COMANDOS BASICOS DE NETSTAT

# 1. Mostrar todas as conexões de rede ativas e suas estatisticas:
$ netstat -a

# 2. Listar todas as conexões de rede e portas de escuta:
$ netstat -an

# 3. Exibir conexões de rede juntamente com PID (identificador de processo):
$ netstat -ano

# 4. Mostrar estatisticas detalhadas das interfaces de rede:
$ netstat -e

# 5. Exibir tabela de roteamento:
$ netstat -r

# 6. Mostrar estatisticas de conexoes TCP:
$ netstat -s

# 7. Exibir conexões TCP apenas:
$ netstat -p tcp